# Generated by Django 5.1.5 on 2025-01-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0002_userprofile_facebook_userprofile_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='background',
            field=models.ImageField(blank=True, upload_to='background_pics'),
        ),
    ]
