# Generated by Django 5.1.5 on 2025-01-29 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0003_userprofile_background'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='display_name',
            new_name='displayname',
        ),
    ]
